// This file is automatically generated. DO NOT EDIT.

package model

type Clrmamepro struct {
	Forcenodump  string `xml:"forcenodump,attr"`
	Forcepacking string `xml:"forcepacking,attr"`
}

type Datafile struct {
	Game    []Game    `xml:"game"`
	Header  Header    `xml:"header"`
	Machine []Machine `xml:"machine"`
}

type Game struct {
	Cloneofid   string   `xml:"cloneofid,attr"`
	ID          string   `xml:"id,attr"`
	Name        string   `xml:"name,attr"`
	Category    []string `xml:"category"`
	Description string   `xml:"description"`
	GameID      []string `xml:"game_id"`
	Rom         []Rom    `xml:"rom"`
}

type Header struct {
	Author      string     `xml:"author"`
	Category    string     `xml:"category"`
	Clrmamepro  Clrmamepro `xml:"clrmamepro"`
	Comment     string     `xml:"comment"`
	Date        string     `xml:"date"`
	Description string     `xml:"description"`
	Email       string     `xml:"email"`
	Homepage    string     `xml:"homepage"`
	ID          int        `xml:"id"`
	Name        string     `xml:"name"`
	Subset      string     `xml:"subset"`
	Url         string     `xml:"url"`
	Version     string     `xml:"version"`
}

type Machine struct {
	Name        string `xml:"name,attr"`
	Description string `xml:"description"`
	Rom         Rom    `xml:"rom"`
}

type Rom struct {
	Crc    string `xml:"crc,attr"`
	Date   string `xml:"date,attr"`
	Header string `xml:"header,attr"`
	Md5    string `xml:"md5,attr"`
	Mia    string `xml:"mia,attr"`
	Name   string `xml:"name,attr"`
	Serial string `xml:"serial,attr"`
	Sha1   string `xml:"sha1,attr"`
	Sha256 string `xml:"sha256,attr"`
	Size   string `xml:"size,attr"`
	Status string `xml:"status,attr"`
}
