// This file is automatically generated. DO NOT EDIT.

package model

type Alt struct {
	Company  string `xml:"company,attr"`
	CharData string `xml:",chardata"`
}

type Hash struct {
	Crc32        string   `xml:"crc32,attr"`
	Md5          string   `xml:"md5,attr"`
	Name         string   `xml:"name,attr"`
	Sha1         string   `xml:"sha1,attr"`
	Type         string   `xml:"type,attr"`
	CharData     string   `xml:",chardata"`
	Alt          []Alt    `xml:"alt"`
	Extrainfo    string   `xml:"extrainfo"`
	Manufacturer []string `xml:"manufacturer"`
	Status       string   `xml:"status"`
	Year         string   `xml:"year"`
}

type Hashfile struct {
	Hash         []Hash   `xml:"hash"`
	Manufacturer []string `xml:"manufacturer"`
	Year         string   `xml:"year"`
}
